---
- name: Deploy K3s and AWX
  hosts: all
  become: yes
  vars:
    awx_namespace: awx
    kubeconfig_path: /etc/rancher/k3s/k3s.yaml # Example for k3s, adjust as needed
    remote_tmp_path: "/tmp/ansible_tmp"
  tasks:
    - name: Open required firewall ports and settings
      ansible.posix.firewalld:
        service: "{{ item.service }}"
        permanent: "{{ item.permanent | default(true) }}"
        state: "{{ item.state | default('enabled') }}"
        zone: "{{ item.zone }}"
        immediate: "{{ item.immediate | default(true) }}"
      loop:
        - { service: 'https', zone: 'public' }
     
    - name: Masquerade 
      ansible.posix.firewalld:
        masquerade: true
        state: enabled
        permanent: true
        zone: public

    - name: Install the latest version of Apache
      ansible.builtin.yum:
        name: "{{ item}}"
        state: latest
      loop:
        - pip
        - tar
        
    - name: Install kubernetes Python library
      pip:
        name: kubernetes
        state: present
    
    - name: Add custom firewall ports
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        zone: public
        immediate: yes
      loop:
        - 8080/tcp
        - 8443/tcp
        - 443/tcp
        - 80/tcp
        - 6443/tcp

    - name: Copy AWX Lab configuration file
      ansible.builtin.copy:
        src: templates/awx-lab.yml
        dest: /root/awx-lab.yml
        owner: root
        group: root
        mode: '0644'

    - name: Copy Kustomization file
      ansible.builtin.copy:
        src: templates/kustomization.yaml
        dest: /root/kustomization.yaml
        owner: root
        group: root
        mode: '0644'

    - name: Allow trusted zones
      firewalld:
        source: "10.0.0.0/8"
        zone: trusted
        state: enabled
        permanent: true
        immediate: yes
      loop_control:
        loop_var: source

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded

    - name: Install K3s
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: "/usr/local/bin/k3s"

    - name: Adjust permissions on the K3s kubeconfig file
      file:
        path: /etc/rancher/k3s/k3s.yaml
        mode: '0644'

    - name: Install git
      package:
        name: git
        state: present

    - name: Install kustomize
      ansible.builtin.shell: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        mv kustomize /usr/local/bin/
      args:
        creates: "/usr/local/bin/kustomize"


    - name: Set kubectl context to the AWX namespace and create name space
      ansible.builtin.shell: |
        export NAMESPACE={{ awx_namespace }}
        kubectl create namespace {{ awx_namespace }}
        kubectl config set-context --namespace={{ awx_namespace }} --current
        kustomize build . | kubectl apply -f -
      ignore_errors: yes

    - name: Apply Kubectl
      ansible.builtin.shell: |
        kubectl apply -k .
      ignore_errors: yes

    - name: Wait for 3 minutes
      ansible.builtin.pause:
        seconds: 180

    - name: List Pods and Servics
      ansible.builtin.shell: |
        kubectl get pods -n awx
        kubectl get svc -n awx
      ignore_errors: yes
